#!/usr/bin/perl 

use File::Glob ':glob';

$installPath = $ARGV[0];
$currDir = `pwd`;
chomp $currDir;

@files = bsd_glob( "Assets/Editor/PostprocessBuildPlayer_*", GLOB_NOCASE );

foreach $file( @files )
{
	if( !( $file =~ m/\./ ) )
	{
		system( "chmod", "755", $file );
		system( $file, $ARGV[0], $ARGV[1], $ARGV[2], $ARGV[3], $ARGV[4], $ARGV[5], $ARGV[6] );
	}
}
